version: '3'

services:
  app:
    build: .
    volumes:
      - .:/ddd_ish
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - /var/lib/postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddd_ish
